//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechCom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public Nullable<int> QuoteID { get; set; }
        public Nullable<int> InventoryID { get; set; }
        public string INserial_No { get; set; }
        public string InventoryName { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> QuotationPrice { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> StockQuantity { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual Quotation Quotation { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
